CREATE TABLE Mission (
    id LONG AUTO_INCREMENT NOT NULL PRIMARY KEY,
    agent VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    gadget1 VARCHAR(255) NOT NULL,
    gadget2 VARCHAR(255) NOT NULL
);